from __future__ import annotations

_PUNCTUATION_TABLE: dict[int, str | int | None] = str.maketrans(
    {
        # Curly quotes
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        # Dashes
        "\u2013": "-",
        "\u2014": "-",
        "\u2212": "-",
        # Spaces
        "\u00a0": " ",
        "\u2002": " ",
        "\u2003": " ",
        "\u2004": " ",
        "\u2005": " ",
        "\u2006": " ",
        "\u2007": " ",
        "\u2008": " ",
        "\u2009": " ",
        "\u200a": " ",
        "\u202f": " ",
        "\u205f": " ",
        "\u3000": " ",
        # Zero-width characters (ZWJ handled in _normalize_punctuation)
        "\u200b": "",
        "\u200c": "",
        "\ufeff": "",
        # Bullet
        "\u2022": "-",
    }  # type: ignore[arg-type]
)

_ES_TABLE: dict[int, str] = {
    ord("ñ"): "n",
    ord("Ñ"): "N",
    ord("¿"): "",
    ord("¡"): "",
}

_PT_TABLE: dict[int, str] = {
    ord("ç"): "c",
    ord("Ç"): "C",
    ord("ã"): "a",
    ord("Ã"): "A",
    ord("õ"): "o",
    ord("Õ"): "O",
    ord("á"): "a",
    ord("Á"): "A",
    ord("é"): "e",
    ord("É"): "E",
    ord("í"): "i",
    ord("Í"): "I",
    ord("ó"): "o",
    ord("Ó"): "O",
    ord("ú"): "u",
    ord("Ú"): "U",
    ord("â"): "a",
    ord("Â"): "A",
    ord("ê"): "e",
    ord("Ê"): "E",
    ord("ô"): "o",
    ord("Ô"): "O",
}

_DE_TABLE: dict[int, str] = {
    ord("ä"): "ae",
    ord("ö"): "oe",
    ord("ü"): "ue",
    ord("Ä"): "Ae",
    ord("Ö"): "Oe",
    ord("Ü"): "Ue",
    ord("ß"): "ss",
}

_FR_IT_TABLE: dict[int, str] = {
    ord("œ"): "oe",
    ord("Œ"): "OE",
    ord("æ"): "ae",
    ord("Æ"): "AE",
    ord("à"): "a",
    ord("À"): "A",
    ord("è"): "e",
    ord("È"): "E",
    ord("ì"): "i",
    ord("Ì"): "I",
    ord("ò"): "o",
    ord("Ò"): "O",
    ord("ù"): "u",
    ord("Ù"): "U",
}

_DEFAULT_TABLE: dict[int, str] = {
    ord("ß"): "ss",
    ord("Æ"): "AE",
    ord("æ"): "ae",
    ord("Œ"): "OE",
    ord("œ"): "oe",
    ord("Ð"): "D",
    ord("ð"): "d",
    ord("Þ"): "TH",
    ord("þ"): "th",
    ord("Ø"): "O",
    ord("ø"): "o",
    ord("Đ"): "D",
    ord("đ"): "d",
    ord("Ł"): "L",
    ord("ł"): "l",
    ord("Ħ"): "H",
    ord("ħ"): "h",
    ord("ı"): "i",
    ord("Ŋ"): "N",
    ord("ŋ"): "n",
    ord("ĸ"): "k",
    ord("Ŧ"): "T",
    ord("ŧ"): "t",
    ord("Ǥ"): "G",
    ord("ǥ"): "g",
    ord("Ǽ"): "AE",
    ord("ǽ"): "ae",
    ord("Ǿ"): "O",
    ord("ǿ"): "o",
    ord("Ȣ"): "OU",
    ord("ȣ"): "ou",
    ord("ȷ"): "j",
    ord("ǝ"): "e",
}

_LANGUAGE_TABLES: dict[str, dict[int, str]] = {
    "es": _ES_TABLE,
    "pt": _PT_TABLE,
    "de": _DE_TABLE,
    "fr": _FR_IT_TABLE,
    "it": _FR_IT_TABLE,
}

_LANG_DETECT_RANGES: dict[str, list[tuple[int, int]]] = {
    "es": [(0x00BF, 0x00BF), (0x00A1, 0x00A1), (0x00F1, 0x00F1), (0x00D1, 0x00D1)],
    "pt": [
        (0x00E7, 0x00E7),
        (0x00C7, 0x00C7),
        (0x00E3, 0x00E3),
        (0x00F5, 0x00F5),
        (0x00C3, 0x00C3),
        (0x00D5, 0x00D5),
    ],
    "de": [
        (0x00FC, 0x00FC),
        (0x00DC, 0x00DC),
        (0x00F6, 0x00F6),
        (0x00D6, 0x00D6),
        (0x00E4, 0x00E4),
        (0x00C4, 0x00C4),
        (0x00DF, 0x00DF),
    ],
    "fr": [(0x0153, 0x0153), (0x0152, 0x0152), (0x00E6, 0x00E6), (0x00C6, 0x00C6)],
    "it": [
        (0x00E0, 0x00E0),
        (0x00E8, 0x00E8),
        (0x00EC, 0x00EC),
        (0x00F2, 0x00F2),
        (0x00F9, 0x00F9),
    ],
}

_EMOJI_TEXT: dict[int, str] = {
    # Faces — smiling
    ord("😀"): "grinning",
    ord("😃"): "smiley",
    ord("😄"): "smile",
    ord("😁"): "grin",
    ord("😆"): "laughing",
    ord("😅"): "sweat-smile",
    ord("🤣"): "rofl",
    ord("😂"): "joy",
    ord("🙂"): "slight-smile",
    ord("🙃"): "upside-down-face",
    ord("😉"): "wink",
    ord("😊"): "blush",
    ord("😇"): "innocent",
    # Faces — affection
    ord("😍"): "heart-eyes",
    ord("🥰"): "smiling-face-with-hearts",
    ord("😘"): "kissing-heart",
    ord("😗"): "kissing",
    ord("☺"): "relaxed",
    ord("😚"): "kissing-closed-eyes",
    ord("😙"): "kissing-smiling-eyes",
    # Faces — cool / positive
    ord("😎"): "smiling-face-with-sunglasses",
    ord("🤩"): "star-struck",
    ord("🥳"): "partying-face",
    ord("😏"): "smirk",
    ord("😌"): "relieved",
    # Faces — negative
    ord("😒"): "unamused",
    ord("🙄"): "rolling-eyes",
    ord("😬"): "grimacing",
    ord("😮"): "open-mouth",
    ord("😯"): "hushed",
    ord("😦"): "frowning",
    ord("😧"): "anguished",
    ord("😢"): "cry",
    ord("😥"): "disappointed-relieved",
    ord("😪"): "sleepy",
    ord("😭"): "sob",
    ord("😱"): "scream",
    ord("😨"): "fearful",
    ord("😰"): "cold-sweat",
    ord("😡"): "rage",
    ord("😠"): "angry",
    ord("🤬"): "face-with-symbols-on-mouth",
    ord("😈"): "smiling-devil",
    ord("👿"): "devil",
    # Faces — neutral / other
    ord("🤔"): "thinking",
    ord("🤨"): "raised-eyebrow",
    ord("😐"): "neutral-face",
    ord("😑"): "expressionless",
    ord("😶"): "no-mouth",
    ord("😴"): "sleeping",
    # Hearts
    ord("❤"): "red-heart",
    ord("🧡"): "orange-heart",
    ord("💛"): "yellow-heart",
    ord("💚"): "green-heart",
    ord("💙"): "blue-heart",
    ord("💜"): "purple-heart",
    ord("🖤"): "black-heart",
    ord("🤍"): "white-heart",
    ord("💔"): "broken-heart",
    ord("❣"): "heart-exclamation",
    ord("💕"): "two-hearts",
    ord("💞"): "revolving-hearts",
    ord("💓"): "heartbeat",
    ord("💗"): "growing-heart",
    ord("💖"): "sparkling-heart",
    ord("💘"): "heart-with-arrow",
    ord("💝"): "heart-with-ribbon",
    # Hands
    ord("👍"): "thumbs-up",
    ord("👎"): "thumbs-down",
    ord("👌"): "ok-hand",
    ord("🤌"): "pinched-fingers",
    ord("🤏"): "pinching-hand",
    ord("✌"): "peace-sign",
    ord("🤞"): "crossed-fingers",
    ord("🤟"): "love-you-gesture",
    ord("🤘"): "metal",
    ord("👈"): "point-left",
    ord("👉"): "point-right",
    ord("👆"): "point-up",
    ord("👇"): "point-down",
    ord("☝"): "point-up-one",
    ord("👋"): "wave",
    ord("🤚"): "raised-back-of-hand",
    ord("🖐"): "raised-hand-with-fingers-splayed",
    ord("✋"): "raised-hand",
    ord("👏"): "clap",
    ord("🙌"): "raised-hands",
    ord("🤝"): "handshake",
    ord("🙏"): "pray",
    ord("✍"): "writing-hand",
    ord("💪"): "muscle",
    ord("🦾"): "mechanical-arm",
    # Celebration / objects
    ord("🎉"): "party-popper",
    ord("🎊"): "confetti-ball",
    ord("🎈"): "balloon",
    ord("🎁"): "gift",
    ord("🎂"): "birthday-cake",
    ord("🍰"): "shortcake",
    ord("🥂"): "clinking-glasses",
    ord("🍻"): "beers",
    ord("🍾"): "bottle-with-popping-cork",
    # Nature / weather
    ord("✨"): "sparkles",
    ord("⭐"): "star",
    ord("🌟"): "glowing-star",
    ord("💫"): "dizzy",
    ord("🔥"): "fire",
    ord("💥"): "collision",
    ord("☀"): "sun",
    ord("🌈"): "rainbow",
    ord("☁"): "cloud",
    ord("⚡"): "zap",
    ord("❄"): "snowflake",
    ord("💧"): "droplet",
    ord("🌊"): "ocean-wave",
    # Animals
    ord("🐱"): "cat-face",
    ord("🐶"): "dog-face",
    ord("🦄"): "unicorn",
    ord("🦋"): "butterfly",
    ord("🐝"): "bee",
    ord("🐢"): "turtle",
    ord("🦉"): "owl",
    ord("🦁"): "lion",
    ord("🐘"): "elephant",
    ord("🦒"): "giraffe",
    # Food / drink
    ord("☕"): "coffee",
    ord("🍵"): "tea",
    ord("🍕"): "pizza",
    ord("🍔"): "hamburger",
    ord("🍟"): "fries",
    ord("🌮"): "taco",
    ord("🌯"): "burrito",
    ord("🍜"): "ramen",
    ord("🍣"): "sushi",
    ord("🍦"): "ice-cream",
    ord("🍩"): "doughnut",
    ord("🍪"): "cookie",
    ord("🍫"): "chocolate-bar",
    ord("🍎"): "apple",
    ord("🍌"): "banana",
    ord("🍇"): "grapes",
    ord("🍉"): "watermelon",
    ord("🥑"): "avocado",
    # Activities / travel
    ord("⚽"): "soccer-ball",
    ord("🏀"): "basketball",
    ord("🏆"): "trophy",
    ord("🥇"): "gold-medal",
    ord("🚀"): "rocket",
    ord("✈"): "airplane",
    ord("🚗"): "car",
    ord("🏠"): "house",
    ord("🏢"): "office-building",
    # Symbols
    ord("💯"): "hundred-points",
    ord("✅"): "check-mark",
    ord("❌"): "cross-mark",
    ord("❓"): "question-mark",
    ord("❗"): "exclamation-mark",
    ord("⚠"): "warning",
    ord("🔔"): "bell",
    ord("🎵"): "musical-note",
    ord("📚"): "books",
    ord("💡"): "light-bulb",
    ord("📌"): "pushpin",
    ord("📍"): "round-pushpin",
    ord("🔗"): "link",
    ord("📧"): "email",
    ord("💬"): "speech-balloon",
    ord("💭"): "thought-balloon",
}

_CONFUSABLES: dict[int, str] = {
    ord("а"): "a",
    ord("А"): "A",
    ord("в"): "B",
    ord("В"): "B",
    ord("е"): "e",
    ord("Е"): "E",
    ord("к"): "K",
    ord("К"): "K",
    ord("м"): "M",
    ord("М"): "M",
    ord("н"): "H",
    ord("Н"): "H",
    ord("о"): "o",
    ord("О"): "O",
    ord("р"): "p",
    ord("Р"): "P",
    ord("с"): "c",
    ord("С"): "C",
    ord("т"): "T",
    ord("Т"): "T",
    ord("х"): "x",
    ord("Х"): "X",
    ord("у"): "y",
    ord("У"): "Y",
    ord("і"): "i",
    ord("І"): "I",
    ord("ј"): "j",
    ord("Ј"): "J",
    ord("ѕ"): "s",
    ord("Ѕ"): "S",
    # Greek → Latin
    ord("α"): "a",
    ord("Α"): "A",
    ord("β"): "b",
    ord("Β"): "B",
    ord("γ"): "g",
    ord("Γ"): "G",
    ord("δ"): "d",
    ord("Δ"): "D",
    ord("ε"): "e",
    ord("Ε"): "E",
    ord("ζ"): "z",
    ord("Ζ"): "Z",
    ord("η"): "i",
    ord("Η"): "I",
    ord("θ"): "th",
    ord("Θ"): "TH",
    ord("ι"): "i",
    ord("Ι"): "I",
    ord("κ"): "k",
    ord("Κ"): "K",
    ord("λ"): "l",
    ord("Λ"): "L",
    ord("μ"): "m",
    ord("Μ"): "M",
    ord("ν"): "n",
    ord("Ν"): "N",
    ord("ξ"): "x",
    ord("Ξ"): "X",
    ord("ο"): "o",
    ord("Ο"): "O",
    ord("π"): "p",
    ord("Π"): "P",
    ord("ρ"): "r",
    ord("Ρ"): "R",
    ord("σ"): "s",
    ord("Σ"): "S",
    ord("τ"): "t",
    ord("Τ"): "T",
    ord("υ"): "y",
    ord("Υ"): "Y",
    ord("φ"): "f",
    ord("Φ"): "F",
    ord("χ"): "ch",
    ord("Χ"): "CH",
    ord("ψ"): "ps",
    ord("Ψ"): "PS",
    ord("ω"): "o",
    ord("Ω"): "O",
}
